checkpoint_path: ./checkpoints/2025-05-12-01-17-55/best_model.pth

task_name: pick_place_us
temporal_agg: True
chunk_size: 32

img_front_topic: /camera_f/color/image_raw
img_left_topic: /camera_l/color/image_raw
img_right_topic: /camera_r/color/image_raw

puppet_arm_left_topic: /puppet/joint_left
puppet_arm_right_topic: /puppet/joint_right

frame_rate: 30


# publish_rate: 40
# arm_steps_length: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.2]
# use_actions_interpolation: False
# max_publish_step: 10000
# pos_lookahead_step: 0
